### ISSUE TITLE
Feature wanted: Add new languages not supported by Google Translate

### ISSUE THREAD

**Issue by jammind** [leolabs/json-autotranslate#17]
Hi,

I want to tell you that json-autotranslate works like charm! I really enjoy it. Recently I have encountered a problem.

I already have my JSON translated into Quechua (Peru Spanish). But it keeps saying "Translation doesn't support pe. Skipping this language." Neither auto-translation nor manual works. I hope it can support languages out of Google Translate's scope. Once I have the folder and JSON ready, it can always use the local resource to translate.

Anyway, I want a walkaround.

**Comment by leolabs** [comment]
Hey @jammind,

could you elaborate on which behavior you'd expect from json-autotranslate in your scenario? I've tried recreating the problem and json-autotranslate translates all other languages just fine, not touching the files that are in unsupported language folders.

**Comment by leolabs** [comment]
I've made a small improvement that may enable the behavior that you're expecting. The dry-run and manual services now don't check languages anymore and thus support any language code you give them. Change is in a0c6f95. Does this solve your problem? :)

**Comment by onionhammer** [comment]
I'm also having an issue where it doesnt support 'fil' for filipino - would this resolve this issue?

**Comment by leolabs** [comment]
That should solve it, as long as the translation service you chose supports the language :)

**Comment by onionhammer** [comment]
No such luck.. "🙈 Google Translate doesn't support fil. Skipping this language." No sure why though, since google translate definitely does support filipino. Sorry to muddy this issue

**Comment by leolabs** [comment]
Hey @onionhammer,
when you go to the [Google Translate](https://translate.google.com/#view=home&op=translate&sl=en&tl=tl) website and select Filipino, you'll see that its language code is `tl` in the URL parameters. Could you try it with that one and see if it works? :)

**Comment by jammind** [comment]
Thanks for the quick response. I have updated json-autotranslate to 1.5.4, but I still get this error:
Google Translate doesn't support "pe". Skipping this language. "pe" here means Peru Espania, which is an ISO locale code.
![image](https://user-images.githubusercontent.com/2723305/78856121-6a753b80-7a58-11ea-88da-d08e54a61b87.png)

**Comment by leolabs** [comment]
Hey, @jammind!
That warning makes sense since `pe` is not supported by Google Translate. All other languages should be automatically translated and the `pe` folder should be left as-is. You can translate it manually if you need it :)

Can you confirm that this is the behavior you're experiencing and elaborate on how you'd expect json-autotranslate to behave in that situation?

**Comment by jammind** [comment]
Indeed. It works like charm! Thank you @leolabs
